kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  disableDefaultCNI: true # disable kindnet
  podSubnet: 10.0.1.0/24 # set to Calico's default subnet
nodes:
- role: control-plane
- role: worker
- role: worker
- role: worker
